development:
  smtp_domain: <%=ENV['SMTP_DOMAIN_DEV']%>
  smtp_user_name: <%=ENV['SMTP_USER_NAME_DEV']%>
  smtp_password: <%=ENV['SMTP_PASSWORD_DEV']%>
  app_domain: <%=ENV['APP_DOMAIN_DEV']%>

production:
  smtp_domain: <%=ENV['SMTP_DOMAIN']%>
  smtp_user_name: <%=ENV['SMTP_USER_NAME']%>
  smtp_password: <%=ENV['SMTP_PASSWORD']%>
  app_domain: <%=ENV['APP_DOMAIN']%>